### ISSUE TITLE
Displaying the overview

### ISSUE THREAD

**Issue by hoalzein** [hoalzein/file-upload#1]
@caugner can you please elaborate on this statement "After uploading such a file, I get an overview of all texts (i.e.,“single-column tables”, such as paragraphs, lists etc.)and tables contained in the file".
It is somehow confusing...maybe with expected mock-up or diagram.
Thanks.

**Comment by caugner** [comment]
You're absolutely right that the instruction is a bit vague.

Let's take the following file as an example: [Lines and tables.docx](https://github.com/hoalzein/file-upload/files/6440288/Lines.and.tables.docx)

The text-and-table extraction will eventually allow the user to choose what parts of the documents to import:

![grafik](https://user-images.githubusercontent.com/495429/117424758-6b5df280-af22-11eb-8b28-78de07154969.png)

Obviously, your solution doesn't have to go that far, but I hope this makes it a bit clearer?

PS: I have to admit that Tika cannot extract tables from PDFs.

**Comment by hoalzein** [comment]
Thank you Claas for the update.
